version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./prisma:/app/prisma
      - ./src:/app/src
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
    external: true
